case: "test_case"
PNP_mode: "SMPNP"
grid_type: "nano_slit_with_reservoirs_2d"
grid:
  equally_spaced_1d:
    pore_radius: 1.0e-8
    pore_length: 5.0e-8
  nano_slit_with_reservoirs_2d:
    pore_radius: 1.0e-8
    pore_length: 5.0e-8
    reservoir_height: 8.0e-8
cation_size: 5.0e-10
anion_size: 5.0e-10
solvent_molecule_size: 5.0e-10
D_anion: 5.0e-9
D_cation: 5.0e-9
surface_potential: 0.3
output_directory: ""
non_dim:
  L_REF: 5.0e-8
  C_REF: 1.0
  D_REF: 5.0e-9
  PHI_REF: 0.02526449777465668
boundary_conditions:
  dirichlet:
    species:
      - 1
    boundary_indices:
      -
        - 1
        - 3
    boundary_values:
      -
        - 0.0
        - 0.001
initial_conditions:
  species:
    - 1
    - 2
    - 3
  values:
    - 0.0
    - 1.0
    - 1.0
solver_parameters:
  verbose: true
  abstol: 1.3e-6
  reltol: 1.0e-10
  maxiters: 100
  reltol_linear: 0.0001
  abstol_linear: 1.0e-8
  method_linear: ~
time_parameters:
  solve_to_steady_state: true
  steady_state_tol: 1.0e-12
  final_time: 1000.0
  max_timestep: 1.0
  initial_timestep: 1.0e-12
