case: "test_case"
PNP_mode: "SMPNP"
grid_type: "nano_slit_with_reservoirs_2d"
grid:
  equally_spaced_1d:
    pore_radius: 1.0e-8
    pore_length: 5.0e-8
  nano_slit_with_reservoirs_2d:
    pore_radius: 1.0e-8
    pore_length: 5.0e-8
    reservoir_height: 8.0e-8
cation_size: 5.0e-10
anion_size: 5.0e-10
solvent_molecule_size: 5.0e-10
D_anion: 5.0e-9
D_cation: 5.0e-9
surface_potential: 0.3
output_directory: ""
non_dim:
  L_REF: 5.0e-8
  C_REF: 1.0
  D_REF: 5.0e-9
  PHI_REF: 0.02526449777465668
